version: '2'
services: 
    angular2:
        image: tanguybusschaert/kandoe_ng2
        ports: 
        - "3000:3000"
    apigateway:
        image: tanguybusschaert/kandoe_gw
        ports: 
        - "5010:5010"
    authservice-db: 
        image: mongo
    authservice:
        image: tanguybusschaert/kandoe_service_auth
        ports: 
        - "5020:5020"
        links: 
        - authservice-db
    userservice-db: 
        image: mongo
    userservice:
        image: tanguybusschaert/kandoe_service_user
        ports: 
        - "5030:5030"
        links:
        - userservice-db
    cardservice-db: 
        image: mongo
    cardservice:
        image: tanguybusschaert/kandoe_service_card
        ports: 
        - "5040:5040"
        links:
        - cardservice-db
    sessionservice-db: 
        image: mongo
    sessionservice:
        image: tanguybusschaert/kandoe_service_session
        ports: 
        - "5050:5050"
        links: 
        - sessionservice-db    
    imageservice:
        image: tanguybusschaert/kandoe_service_image
        ports:
        - "5060:5060"    
